### ISSUE TITLE
Ruby-Band in Rails application

### ISSUE THREAD

**Issue by tranhv** [arrigonialberto86/ruby-band#15]
Hi,

I would like to use ruby-band gem in rails app (ruby 2.1.3p242, Rails 4.2.1).
When i run by irb:

```
hvt@hvts-macpro:~/ck (master)$ irb
irb(main):001:0> require 'ruby-band'
LoadError: cannot load such file -- java
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:120:in `require'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:120:in `require'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jbundler-0.4.3/lib/jbundler/pom.rb:24:in `<top (required)>'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jbundler-0.4.3/lib/jbundler/gemfile_lock.rb:22:in `<top (required)>'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:68:in `require'
```

Version ruby-band in gem list: ruby-band (0.1.13)

What should i do?

Thanks,
Tran

**Comment by tranhv** [comment]
Hi,

The issue java load is resolved.
I have one new issue about ruby-band:

```
hvt@hvts-macpro:~/ck (master)$ ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
hvt@hvts-macpro:~/ck (master)$ irb
irb(main):001:0> require 'ruby-band'
NameError: uninitialized constant JBundler::AetherRuby::NativeException
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jbundler-0.4.3/lib/jbundler/aether.rb:59:in `rescue in initialize'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jbundler-0.4.3/lib/jbundler/aether.rb:50:in `initialize'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jbundler-0.4.3/lib/jbundler.rb:36:in `new'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jbundler-0.4.3/lib/jbundler.rb:36:in `<top (required)>'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/ruby-band-0.1.13/lib/ruby-band.rb:3:in `<top (required)>'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:133:in `require'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    from /Users/hvt/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from (irb):1
    from /Users/hvt/.rbenv/versions/2.1.3/bin/irb:11:in `<main>'

```

Please help me.

Thanks,
Tran

**Comment by paulgoetze** [comment]
Hi @tranhv, ruby-band only works with JRuby. It looks like you are using C-Ruby. 
There might be some other issues even on JRuby (see the current issues list for this project). 

Also this project seems to be unmaintained.
You can try the [weka gem](https://github.com/paulgoetze/weka-jruby) which uses most of the ideas of ruby-band and should work with an up-to-date JRuby version.

In case you want to give the weka gem a try, I’ll be happy to help, if there are any issues popping up.
